// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

pub const LINEAR_MASK: u32 = 25_087;
pub const ALL_FORMATS_MASK: u32 = 163_839;
pub const EAN_ADDON_READ_FLAG: u32 = 32_768;
pub const EAN_ADDON_REQUIRE_FLAG: u32 = 65_536;
