// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
export const formatBits = {
  EAN13: 1,
  UPCA: 2,
  EAN8: 4,
  UPCE: 8,
  Code128: 16,
  Code39: 32,
  ITF: 64,
  Codabar: 128,
  Code93: 256,
  QRCode: 512,
  DataMatrix: 1024,
  PDF417: 2048,
  Aztec: 4096,
  DataBar: 8192,
  DataBarExpanded: 16384,
  MaxiCode: 131072,
} as const;
export type Format = keyof typeof formatBits;
export const retailFormats: readonly Format[] = ["EAN13", "UPCA", "EAN8", "UPCE"];
export const commonLinearFormats: readonly Format[] = [
  "EAN13",
  "UPCA",
  "EAN8",
  "UPCE",
  "Code128",
  "Code39",
  "ITF",
];
export const commonFormats: readonly Format[] = [
  "EAN13",
  "UPCA",
  "EAN8",
  "UPCE",
  "Code128",
  "Code39",
  "ITF",
  "QRCode",
  "DataMatrix",
];
export const linearFormats: readonly Format[] = [
  "EAN13",
  "UPCA",
  "EAN8",
  "UPCE",
  "Code128",
  "Code39",
  "ITF",
  "Codabar",
  "Code93",
  "DataBar",
  "DataBarExpanded",
];
export const matrixFormats: readonly Format[] = [
  "QRCode",
  "DataMatrix",
  "PDF417",
  "Aztec",
  "MaxiCode",
];
export const eanAddOnReadFlag = 32768;
export const eanAddOnRequireFlag = 65536;
