// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

/// A supported barcode symbology. Discriminants are native format-mask bits.
#[derive(Clone, Copy, Debug, serde::Deserialize, Eq, PartialEq)]
#[repr(u32)]
pub enum Format {
    #[serde(rename = "EAN13")]
    /// EAN-13 retail barcode.
    Ean13 = 1,
    #[serde(rename = "UPCA")]
    /// UPC-A retail barcode.
    Upca = 2,
    #[serde(rename = "EAN8")]
    /// EAN-8 retail barcode.
    Ean8 = 4,
    #[serde(rename = "UPCE")]
    /// UPC-E compressed retail barcode.
    Upce = 8,
    /// Code 128, including GS1-128.
    Code128 = 16,
    /// Code 39.
    Code39 = 32,
    #[serde(rename = "ITF")]
    /// Interleaved 2 of 5.
    Itf = 64,
    /// Codabar.
    Codabar = 128,
    /// Code 93.
    Code93 = 256,
    #[serde(rename = "QRCode")]
    /// QR Code.
    QrCode = 512,
    /// Data Matrix.
    DataMatrix = 1_024,
    #[serde(rename = "PDF417")]
    /// PDF417 stacked barcode.
    Pdf417 = 2_048,
    /// Aztec Code, including supported Aztec Rune reads.
    Aztec = 4_096,
    /// GS1 `DataBar`.
    DataBar = 8_192,
    /// GS1 `DataBar` Expanded.
    DataBarExpanded = 16_384,
    /// `MaxiCode`.
    MaxiCode = 131_072,
}

pub(crate) const RETAIL_MASK: u32 = 15;
pub(crate) const COMMON_LINEAR_MASK: u32 = 127;
pub(crate) const COMMON_MASK: u32 = 1_663;
pub(crate) const LINEAR_MASK: u32 = 25_087;
pub(crate) const MATRIX_MASK: u32 = 138_752;
pub(crate) const ALL_FORMATS_MASK: u32 = LINEAR_MASK | MATRIX_MASK;
