[package]
name="barcode-research-core"
version="0.0.0"
edition="2021"
publish=false
[lib]
crate-type=["cdylib","rlib"]
[profile.release]
lto=true
codegen-units=1
panic="abort"
[dependencies]
barcode-multiformat={path="../multiformat"}
[features]
default = ["mode-medium"]
"mode-low" = []
"mode-medium" = []
"mode-high" = []
"mode-very-high" = []
"native-timing" = []
"diagnostic-retry-trace" = []
"diagnostic-tile-events" = []
