/* Generated by scripts/generate_formats.py from config/formats.json. Do not edit. */
#ifndef TAPIRSCAN_FORMATS_H
#define TAPIRSCAN_FORMATS_H
#define TAPIRSCAN_FORMAT_EAN13 1u /* EAN-13 retail barcode. */
#define TAPIRSCAN_FORMAT_UPCA 2u /* UPC-A retail barcode. */
#define TAPIRSCAN_FORMAT_EAN8 4u /* EAN-8 retail barcode. */
#define TAPIRSCAN_FORMAT_UPCE 8u /* UPC-E compressed retail barcode. */
#define TAPIRSCAN_FORMAT_CODE128 16u /* Code 128, including GS1-128. */
#define TAPIRSCAN_FORMAT_CODE39 32u /* Code 39. */
#define TAPIRSCAN_FORMAT_ITF 64u /* Interleaved 2 of 5. */
#define TAPIRSCAN_FORMAT_CODABAR 128u /* Codabar. */
#define TAPIRSCAN_FORMAT_CODE93 256u /* Code 93. */
#define TAPIRSCAN_FORMAT_QR_CODE 512u /* QR Code. */
#define TAPIRSCAN_FORMAT_DATA_MATRIX 1024u /* Data Matrix. */
#define TAPIRSCAN_FORMAT_PDF417 2048u /* PDF417 stacked barcode. */
#define TAPIRSCAN_FORMAT_AZTEC 4096u /* Aztec Code, including supported Aztec Rune reads. */
#define TAPIRSCAN_FORMAT_DATA_BAR 8192u /* GS1 `DataBar`. */
#define TAPIRSCAN_FORMAT_DATA_BAR_EXPANDED 16384u /* GS1 `DataBar` Expanded. */
#define TAPIRSCAN_FORMAT_MAXI_CODE 131072u /* `MaxiCode`. */

#define TAPIRSCAN_FORMATS_RETAIL 15u /* EAN-13, UPC-A, EAN-8 and UPC-E. */
#define TAPIRSCAN_FORMATS_COMMON_1D 127u /* Retail formats plus Code 128, Code 39 and ITF. */
#define TAPIRSCAN_FORMATS_COMMON 1663u /* Common linear formats plus QR Code and Data Matrix. */
#define TAPIRSCAN_FORMATS_LINEAR 25087u /* All supported linear formats, including DataBar variants. */
#define TAPIRSCAN_FORMATS_MATRIX 138752u /* QR Code, Data Matrix, PDF417, Aztec and MaxiCode. */
#define TAPIRSCAN_FORMATS_ALL 163839u /* Every supported format. */
#endif
