#!/usr/bin/env python3
"""Generate synchronized format declarations for every language binding."""
# ruff: noqa: E501

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/formats.json"
OUTPUTS = {
    ROOT / "bindings/rust/src/format_registry.rs": "rust_registry",
    ROOT / "bindings/rust/api/format.rs": "rust_format",
    ROOT / "bindings/javascript/src/multiformat/format-registry.ts": "typescript",
    ROOT / "bindings/c/include/tapirscan_formats.h": "c",
    ROOT / "bindings/cpp/include/tapirscan/format.hpp": "cpp",
    ROOT / "bindings/java/src/main/java/org/tapirscan/Format.java": "java",
}
PRESETS = (
    ("retail", "RETAIL", "EAN-13, UPC-A, EAN-8 and UPC-E."),
    ("common1D", "COMMON_1D", "Retail formats plus Code 128, Code 39 and ITF."),
    ("common", "COMMON", "Common linear formats plus QR Code and Data Matrix."),
    ("1D", "LINEAR", "All supported linear formats, including DataBar variants."),
    ("2D", "MATRIX", "QR Code, Data Matrix, PDF417, Aztec and MaxiCode."),
)
FORMAT_COUNT = 16


def validate_registry(registry: dict[str, Any]) -> None:  # noqa: C901
    """Reject ambiguous or incomplete registry values."""
    formats = registry["formats"]
    names = [item[0] for item in formats]
    variants = [item[1] for item in formats]
    bits = [item[2] for item in formats]
    if (
        len(formats) != FORMAT_COUNT
        or len(set(names)) != FORMAT_COUNT
        or len(set(variants)) != FORMAT_COUNT
    ):
        msg = "Format names and Rust variants must contain 16 unique values"
        raise ValueError(msg)
    if any(not isinstance(bit, int) or bit <= 0 or bit & (bit - 1) for bit in bits):
        msg = "Format bits must be positive, distinct powers of two"
        raise ValueError(msg)
    if len(set(bits)) != len(bits):
        msg = "Format bits must be unique"
        raise ValueError(msg)
    presets = registry["presets"]
    if set(presets) != {"retail", "common1D", "common", "1D", "2D"}:
        msg = "Format presets must match the public selector names"
        raise ValueError(msg)
    for preset, members in presets.items():
        if (
            not members
            or len(members) != len(set(members))
            or any(n not in names for n in members)
        ):
            msg = f"Invalid format preset: {preset}"
            raise ValueError(msg)
    for child, parent in [
        ("common1D", "retail"),
        ("common", "common1D"),
        ("1D", "common1D"),
    ]:
        if presets[child][: len(presets[parent])] != presets[parent]:
            msg = f"{parent} must be an ordered prefix of {child}"
            raise ValueError(msg)
    flags = list(registry["engineFlags"].values())
    if (
        len(flags) != len(set(flags))
        or any(
            not isinstance(flag, int) or flag <= 0 or flag & (flag - 1)
            for flag in flags
        )
        or any(flag in bits for flag in flags)
    ):
        msg = "Engine flags must be distinct from formats and each other"
        raise ValueError(msg)
    linear = set(registry["presets"]["1D"])
    matrix = set(registry["presets"]["2D"])
    if linear & matrix or linear | matrix != set(names):
        msg = "1D and 2D presets must partition every format"
        raise ValueError(msg)


def load_registry(path: Path = CONFIG) -> dict[str, Any]:
    """Load and validate the compact registry schema."""
    registry = json.loads(path.read_text())
    validate_registry(registry)
    return registry


def rust_registry_source(registry: dict[str, Any]) -> str:
    """Render masks and engine flags consumed by the private facade."""
    presets = registry["presets"]
    bits: dict[str, int] = {
        str(name): int(bit) for name, _, bit, _ in registry["formats"]
    }

    def mask(names: list[str]) -> int:
        return sum(bits[name] for name in names)

    flags = registry["engineFlags"]
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

pub const LINEAR_MASK: u32 = {mask(presets["1D"]):_};
pub const ALL_FORMATS_MASK: u32 = {mask(presets["1D"] + presets["2D"]):_};
pub const EAN_ADDON_READ_FLAG: u32 = {flags["eanAddOnRead"]:_};
pub const EAN_ADDON_REQUIRE_FLAG: u32 = {flags["eanAddOnRequire"]:_};
"""


def rust_format_source(registry: dict[str, Any]) -> str:
    """Render the documented public Rust format enum."""
    presets = registry["presets"]
    bits: dict[str, int] = {
        str(name): int(bit) for name, _, bit, _ in registry["formats"]
    }

    def mask(names: list[str]) -> int:
        return sum(bits[name] for name in names)

    variants = []
    names = []
    every = "".join(f"\n        Self::{item[1]}," for item in registry["formats"])
    for name, variant, bit, description in registry["formats"]:
        rename = f'    #[serde(rename = "{name}")]\n' if name != variant else ""
        variants.append(f"{rename}    /// {description}\n    {variant} = {bit:_},")
        names.append(f'            Self::{variant} => "{name}",')
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

/// A supported barcode symbology. Discriminants are native format-mask bits.
#[derive(Clone, Copy, Debug, serde::Deserialize, serde::Serialize, Eq, PartialEq)]
#[repr(u32)]
pub enum Format {{
{chr(10).join(variants)}
}}

impl Format {{
    /// Every supported format in native bit order.
    pub const ALL: [Self; {len(registry["formats"])}] = [{every}
    ];

    /// Stable schema name used by language adapters.
    #[must_use]
    pub const fn as_str(self) -> &'static str {{
        match self {{
{chr(10).join(names)}
        }}
    }}
}}

pub(crate) const RETAIL_MASK: u32 = {mask(presets["retail"]):_};
pub(crate) const COMMON_LINEAR_MASK: u32 = {mask(presets["common1D"]):_};
pub(crate) const COMMON_MASK: u32 = {mask(presets["common"]):_};
pub(crate) const LINEAR_MASK: u32 = {mask(presets["1D"]):_};
pub(crate) const MATRIX_MASK: u32 = {mask(presets["2D"]):_};
pub(crate) const ALL_FORMATS_MASK: u32 = LINEAR_MASK | MATRIX_MASK;
"""


def typescript_source(registry: dict[str, Any]) -> str:
    """Render TypeScript declarations consumed by the public resolver."""
    formats = registry["formats"]
    presets = registry["presets"]
    flags = registry["engineFlags"]
    bits = "\n".join(f"  {name}: {bit}," for name, _, bit, _ in formats)

    def array(key: str) -> str:
        values = presets[key]
        if key == "retail":
            return json.dumps(values, separators=(", ", ": "))
        rows = "\n".join(f'  "{name}",' for name in values)
        return f"[\n{rows}\n]"

    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
export const formatBits = {{
{bits}
}} as const;
export type Format = keyof typeof formatBits;
export const retailFormats: readonly Format[] = {array("retail")};
export const commonLinearFormats: readonly Format[] = {array("common1D")};
export const commonFormats: readonly Format[] = {array("common")};
export const linearFormats: readonly Format[] = {array("1D")};
export const matrixFormats: readonly Format[] = {array("2D")};
export const eanAddOnReadFlag = {flags["eanAddOnRead"]};
export const eanAddOnRequireFlag = {flags["eanAddOnRequire"]};
"""


def constant(variant: str) -> str:
    """Convert a Rust variant such as `QrCode` to `QR_CODE`."""
    return "".join(
        f"_{char}"
        if char.isupper() and index and variant[index - 1].islower()
        else char
        for index, char in enumerate(variant)
    ).upper()


def preset_masks(registry: dict[str, Any]) -> list[tuple[str, int, str]]:
    """Return each named preset with its mask and description."""
    bits = {str(name): int(bit) for name, _, bit, _ in registry["formats"]}
    presets = registry["presets"]
    masks = [
        (name, sum(bits[f] for f in presets[key]), text) for key, name, text in PRESETS
    ]
    every = sum(bits.values())
    return [*masks, ("ALL", every, "Every supported format.")]


def c_source(registry: dict[str, Any]) -> str:
    """Render C format bits and preset masks."""
    formats = "\n".join(
        f"#define TAPIRSCAN_FORMAT_{constant(variant)} {bit}u /* {text} */"
        for _, variant, bit, text in registry["formats"]
    )
    presets = "\n".join(
        f"#define TAPIRSCAN_FORMATS_{name} {mask}u /* {text} */"
        for name, mask, text in preset_masks(registry)
    )
    return f"""/* Generated by scripts/generate_formats.py from config/formats.json. Do not edit. */
#ifndef TAPIRSCAN_FORMATS_H
#define TAPIRSCAN_FORMATS_H
{formats}

{presets}
#endif
"""


def cpp_source(registry: dict[str, Any]) -> str:
    """Render the C++ format enum."""
    variants = "\n".join(
        f"    {variant} = TAPIRSCAN_FORMAT_{constant(variant)},"
        for _, variant, _, _ in registry["formats"]
    )
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
#pragma once
#include <tapirscan.h>
#include <cstdint>

namespace tapirscan {{
/// A supported barcode symbology. Values are native format-mask bits.
enum class Format : std::uint32_t {{
{variants}
}};
}}  // namespace tapirscan
"""


def java_source(registry: dict[str, Any]) -> str:
    """Render the Java format enum and preset sets."""
    constants = ",\n".join(
        f'    /** {text} */\n    {constant(variant)}({bit}, "{name}")'
        for name, variant, bit, text in registry["formats"]
    )
    by_name = {
        str(name): constant(variant) for name, variant, _, _ in registry["formats"]
    }
    presets = []
    for key, preset, text in PRESETS:
        members = ", ".join(by_name[name] for name in registry["presets"][key])
        presets.append(
            f"    /** {text} */\n"
            f"    public static final Set<Format> {preset} =\n"
            f"        Collections.unmodifiableSet(EnumSet.of({members}));"
        )
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
package org.tapirscan;

import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

/** A supported barcode symbology. */
public enum Format {{
{constants};

{chr(10).join(presets)}
    /** Every supported format. */
    public static final Set<Format> ALL = Collections.unmodifiableSet(EnumSet.allOf(Format.class));

    private final int bit;
    private final String schemaName;

    Format(int bit, String schemaName) {{
        this.bit = bit;
        this.schemaName = schemaName;
    }}

    /** Native format-mask bit. */
    public int bit() {{
        return bit;
    }}

    /** Stable name shared with the other language bindings, such as {{@code "QRCode"}}. */
    @Override
    public String toString() {{
        return schemaName;
    }}

    static int mask(Set<Format> formats) {{
        int mask = 0;
        for (Format format : formats) mask |= format.bit;
        return mask;
    }}

    static Format fromBit(int bit) {{
        for (Format format : values()) if (format.bit == bit) return format;
        throw new IllegalStateException("Unknown native format " + bit);
    }}
}}
"""


def generated_sources(registry: dict[str, Any]) -> dict[Path, str]:
    """Return every generated path and its deterministic contents."""
    renderers = {
        "rust_registry": rust_registry_source,
        "rust_format": rust_format_source,
        "typescript": typescript_source,
        "c": c_source,
        "cpp": cpp_source,
        "java": java_source,
    }
    return {path: renderers[kind](registry) for path, kind in OUTPUTS.items()}


def main() -> int:
    """Write generated declarations or report drift without changing files."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = False
    for path, expected in generated_sources(load_registry()).items():
        actual = path.read_bytes().decode() if path.exists() else ""
        if actual == expected:
            continue
        changed = True
        if args.check:
            sys.stdout.writelines(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected.encode())
    return int(args.check and changed)


if __name__ == "__main__":
    raise SystemExit(main())
