#!/usr/bin/env python3
"""Generate synchronized Rust and TypeScript format declarations."""
# ruff: noqa: E501

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/formats.json"
OUTPUTS = {
    ROOT / "bindings/rust/src/format_registry.rs": "rust_registry",
    ROOT / "bindings/rust/api/format.rs": "rust_format",
    ROOT / "bindings/javascript/src/multiformat/format-registry.ts": "typescript",
}
FORMAT_COUNT = 16


def validate_registry(registry: dict[str, Any]) -> None:  # noqa: C901
    """Reject ambiguous or incomplete registry values."""
    formats = registry["formats"]
    names = [item[0] for item in formats]
    variants = [item[1] for item in formats]
    bits = [item[2] for item in formats]
    if (
        len(formats) != FORMAT_COUNT
        or len(set(names)) != FORMAT_COUNT
        or len(set(variants)) != FORMAT_COUNT
    ):
        msg = "Format names and Rust variants must contain 16 unique values"
        raise ValueError(msg)
    if any(not isinstance(bit, int) or bit <= 0 or bit & (bit - 1) for bit in bits):
        msg = "Format bits must be positive, distinct powers of two"
        raise ValueError(msg)
    if len(set(bits)) != len(bits):
        msg = "Format bits must be unique"
        raise ValueError(msg)
    presets = registry["presets"]
    if set(presets) != {"retail", "common1D", "common", "1D", "2D"}:
        msg = "Format presets must match the public selector names"
        raise ValueError(msg)
    for preset, members in presets.items():
        if (
            not members
            or len(members) != len(set(members))
            or any(n not in names for n in members)
        ):
            msg = f"Invalid format preset: {preset}"
            raise ValueError(msg)
    for child, parent in [
        ("common1D", "retail"),
        ("common", "common1D"),
        ("1D", "common1D"),
    ]:
        if presets[child][: len(presets[parent])] != presets[parent]:
            msg = f"{parent} must be an ordered prefix of {child}"
            raise ValueError(msg)
    flags = list(registry["engineFlags"].values())
    if (
        len(flags) != len(set(flags))
        or any(
            not isinstance(flag, int) or flag <= 0 or flag & (flag - 1)
            for flag in flags
        )
        or any(flag in bits for flag in flags)
    ):
        msg = "Engine flags must be distinct from formats and each other"
        raise ValueError(msg)
    linear = set(registry["presets"]["1D"])
    matrix = set(registry["presets"]["2D"])
    if linear & matrix or linear | matrix != set(names):
        msg = "1D and 2D presets must partition every format"
        raise ValueError(msg)


def load_registry(path: Path = CONFIG) -> dict[str, Any]:
    """Load and validate the compact registry schema."""
    registry = json.loads(path.read_text())
    validate_registry(registry)
    return registry


def rust_registry_source(registry: dict[str, Any]) -> str:
    """Render masks and engine flags consumed by the private facade."""
    presets = registry["presets"]
    bits: dict[str, int] = {
        str(name): int(bit) for name, _, bit, _ in registry["formats"]
    }

    def mask(names: list[str]) -> int:
        return sum(bits[name] for name in names)

    flags = registry["engineFlags"]
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

pub const LINEAR_MASK: u32 = {mask(presets["1D"]):_};
pub const ALL_FORMATS_MASK: u32 = {mask(presets["1D"] + presets["2D"]):_};
pub const EAN_ADDON_READ_FLAG: u32 = {flags["eanAddOnRead"]:_};
pub const EAN_ADDON_REQUIRE_FLAG: u32 = {flags["eanAddOnRequire"]:_};
"""


def rust_format_source(registry: dict[str, Any]) -> str:
    """Render the documented public Rust format enum."""
    presets = registry["presets"]
    bits: dict[str, int] = {
        str(name): int(bit) for name, _, bit, _ in registry["formats"]
    }

    def mask(names: list[str]) -> int:
        return sum(bits[name] for name in names)

    variants = []
    names = []
    for name, variant, bit, description in registry["formats"]:
        rename = f'    #[serde(rename = "{name}")]\n' if name != variant else ""
        variants.append(f"{rename}    /// {description}\n    {variant} = {bit:_},")
        names.append(f'            Self::{variant} => "{name}",')
    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.

/// A supported barcode symbology. Discriminants are native format-mask bits.
#[derive(Clone, Copy, Debug, serde::Deserialize, Eq, PartialEq)]
#[repr(u32)]
pub enum Format {{
{chr(10).join(variants)}
}}

impl Format {{
    /// Stable schema name used by language adapters.
    #[must_use]
    pub const fn as_str(self) -> &'static str {{
        match self {{
{chr(10).join(names)}
        }}
    }}
}}

pub(crate) const RETAIL_MASK: u32 = {mask(presets["retail"]):_};
pub(crate) const COMMON_LINEAR_MASK: u32 = {mask(presets["common1D"]):_};
pub(crate) const COMMON_MASK: u32 = {mask(presets["common"]):_};
pub(crate) const LINEAR_MASK: u32 = {mask(presets["1D"]):_};
pub(crate) const MATRIX_MASK: u32 = {mask(presets["2D"]):_};
pub(crate) const ALL_FORMATS_MASK: u32 = LINEAR_MASK | MATRIX_MASK;
"""


def typescript_source(registry: dict[str, Any]) -> str:
    """Render TypeScript declarations consumed by the public resolver."""
    formats = registry["formats"]
    presets = registry["presets"]
    flags = registry["engineFlags"]
    bits = "\n".join(f"  {name}: {bit}," for name, _, bit, _ in formats)

    def array(key: str) -> str:
        values = presets[key]
        if key == "retail":
            return json.dumps(values, separators=(", ", ": "))
        rows = "\n".join(f'  "{name}",' for name in values)
        return f"[\n{rows}\n]"

    return f"""// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
export const formatBits = {{
{bits}
}} as const;
export type Format = keyof typeof formatBits;
export const retailFormats: readonly Format[] = {array("retail")};
export const commonLinearFormats: readonly Format[] = {array("common1D")};
export const commonFormats: readonly Format[] = {array("common")};
export const linearFormats: readonly Format[] = {array("1D")};
export const matrixFormats: readonly Format[] = {array("2D")};
export const eanAddOnReadFlag = {flags["eanAddOnRead"]};
export const eanAddOnRequireFlag = {flags["eanAddOnRequire"]};
"""


def generated_sources(registry: dict[str, Any]) -> dict[Path, str]:
    """Return every generated path and its deterministic contents."""
    renderers = {
        "rust_registry": rust_registry_source,
        "rust_format": rust_format_source,
        "typescript": typescript_source,
    }
    return {path: renderers[kind](registry) for path, kind in OUTPUTS.items()}


def main() -> int:
    """Write generated declarations or report drift without changing files."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = False
    for path, expected in generated_sources(load_registry()).items():
        actual = path.read_bytes().decode() if path.exists() else ""
        if actual == expected:
            continue
        changed = True
        if args.check:
            sys.stdout.writelines(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(path),
                    tofile=f"{path} (generated)",
                )
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected.encode())
    return int(args.check and changed)


if __name__ == "__main__":
    raise SystemExit(main())
