[build]
  publish = "dist"

[[redirects]]
  from = "https://tapirscan.netlify.app/*"
  to = "https://tapirscan.f-kleinicke.de/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tapirscan.netlify.app/*"
  to = "https://tapirscan.f-kleinicke.de/:splat"
  status = 301
  force = true
