// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
package org.tapirscan;

import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

/** A supported barcode symbology. */
public enum Format {
    /** EAN-13 retail barcode. */
    EAN13(1, "EAN13"),
    /** UPC-A retail barcode. */
    UPCA(2, "UPCA"),
    /** EAN-8 retail barcode. */
    EAN8(4, "EAN8"),
    /** UPC-E compressed retail barcode. */
    UPCE(8, "UPCE"),
    /** Code 128, including GS1-128. */
    CODE128(16, "Code128"),
    /** Code 39. */
    CODE39(32, "Code39"),
    /** Interleaved 2 of 5. */
    ITF(64, "ITF"),
    /** Codabar. */
    CODABAR(128, "Codabar"),
    /** Code 93. */
    CODE93(256, "Code93"),
    /** QR Code. */
    QR_CODE(512, "QRCode"),
    /** Data Matrix. */
    DATA_MATRIX(1024, "DataMatrix"),
    /** PDF417 stacked barcode. */
    PDF417(2048, "PDF417"),
    /** Aztec Code, including supported Aztec Rune reads. */
    AZTEC(4096, "Aztec"),
    /** GS1 `DataBar`. */
    DATA_BAR(8192, "DataBar"),
    /** GS1 `DataBar` Expanded. */
    DATA_BAR_EXPANDED(16384, "DataBarExpanded"),
    /** `MaxiCode`. */
    MAXI_CODE(131072, "MaxiCode");

    /** EAN-13, UPC-A, EAN-8 and UPC-E. */
    public static final Set<Format> RETAIL =
        Collections.unmodifiableSet(EnumSet.of(EAN13, UPCA, EAN8, UPCE));
    /** Retail formats plus Code 128, Code 39 and ITF. */
    public static final Set<Format> COMMON_1D =
        Collections.unmodifiableSet(EnumSet.of(EAN13, UPCA, EAN8, UPCE, CODE128, CODE39, ITF));
    /** Common linear formats plus QR Code and Data Matrix. */
    public static final Set<Format> COMMON =
        Collections.unmodifiableSet(EnumSet.of(EAN13, UPCA, EAN8, UPCE, CODE128, CODE39, ITF, QR_CODE, DATA_MATRIX));
    /** All supported linear formats, including DataBar variants. */
    public static final Set<Format> LINEAR =
        Collections.unmodifiableSet(EnumSet.of(EAN13, UPCA, EAN8, UPCE, CODE128, CODE39, ITF, CODABAR, CODE93, DATA_BAR, DATA_BAR_EXPANDED));
    /** QR Code, Data Matrix, PDF417, Aztec and MaxiCode. */
    public static final Set<Format> MATRIX =
        Collections.unmodifiableSet(EnumSet.of(QR_CODE, DATA_MATRIX, PDF417, AZTEC, MAXI_CODE));
    /** Every supported format. */
    public static final Set<Format> ALL = Collections.unmodifiableSet(EnumSet.allOf(Format.class));

    private final int bit;
    private final String schemaName;

    Format(int bit, String schemaName) {
        this.bit = bit;
        this.schemaName = schemaName;
    }

    /** Native format-mask bit. */
    public int bit() {
        return bit;
    }

    /** Stable name shared with the other language bindings, such as {@code "QRCode"}. */
    @Override
    public String toString() {
        return schemaName;
    }

    static int mask(Set<Format> formats) {
        int mask = 0;
        for (Format format : formats) mask |= format.bit;
        return mask;
    }

    static Format fromBit(int bit) {
        for (Format format : values()) if (format.bit == bit) return format;
        throw new IllegalStateException("Unknown native format " + bit);
    }
}
