// Generated by scripts/generate_formats.py from config/formats.json. Do not edit.
#pragma once
#include <tapirscan.h>
#include <cstdint>

namespace tapirscan {
/// A supported barcode symbology. Values are native format-mask bits.
enum class Format : std::uint32_t {
    Ean13 = TAPIRSCAN_FORMAT_EAN13,
    Upca = TAPIRSCAN_FORMAT_UPCA,
    Ean8 = TAPIRSCAN_FORMAT_EAN8,
    Upce = TAPIRSCAN_FORMAT_UPCE,
    Code128 = TAPIRSCAN_FORMAT_CODE128,
    Code39 = TAPIRSCAN_FORMAT_CODE39,
    Itf = TAPIRSCAN_FORMAT_ITF,
    Codabar = TAPIRSCAN_FORMAT_CODABAR,
    Code93 = TAPIRSCAN_FORMAT_CODE93,
    QrCode = TAPIRSCAN_FORMAT_QR_CODE,
    DataMatrix = TAPIRSCAN_FORMAT_DATA_MATRIX,
    Pdf417 = TAPIRSCAN_FORMAT_PDF417,
    Aztec = TAPIRSCAN_FORMAT_AZTEC,
    DataBar = TAPIRSCAN_FORMAT_DATA_BAR,
    DataBarExpanded = TAPIRSCAN_FORMAT_DATA_BAR_EXPANDED,
    MaxiCode = TAPIRSCAN_FORMAT_MAXI_CODE,
};
}  // namespace tapirscan
